### ISSUE TITLE
로그, 에러환경 구축

### ISSUE THREAD

**Issue by sominyun** [iTpple-S-POT/backend#1]
## 📝 Content
- 로그환경구축
- 에러환경구축
## ✅ TODO
- [ ] 로그환경 구축( logback으로 로그 정제 필요함)
- [ ] 에러환경구축 
- [ ] 예시로 error 500 만듦
- [ ] localhost:8080/api/members/ex로 접속하면 json이 뜨도록
