### ISSUE TITLE
S3 presigned URL 업로드 구현 및 팟 업로드 관련 비즈니스 로직 구현

### ISSUE THREAD

**Issue by junchanpp** [iTpple-S-POT/backend#22]
## 📝 Content

- S3 presigned URL 업로드 구현
- 카테고리 설정 과정 부터 팟 업로드 까지 구현
## ✅ TODO

- [x] S3 presigned URL 업로드 구현
- [x] 카테고리 설정부터 팟 업로드까지 비즈니스 로직 구현
- [x] 테스트 코드 구현
