### ISSUE TITLE
[Fix] 초기유저정보에 status 추가, 에러 수정

### ISSUE THREAD

**Issue by sominyun** [iTpple-S-POT/backend#53]
## 📝 Content

- 초기유저정보 저장 시 필수값인 생년월일이 없을시 status값 PROGRESS로 존재할 시 COMPLETED
- 나머지 정보들은 건너뛰기 가능(nullable)하여 정보가 없을 시 nullable로 저장하고 COMPLETED로 표시
- userId를 이용하여 초기유저정보 값 저장
- 

## ✅ TODO

- [ ] status 추가하여 진행상태 표시 기능 구현
- [ ] userDto response와 request 구현
- [ ] userInfoServiceImpl, userInfoService 구현
