### ISSUE TITLE
POT 조회 최근 본 팟 리스트 로직 구현 및 해시태그 추가

### ISSUE THREAD

**Issue by junchanpp** [iTpple-S-POT/backend#59]
## 📝 Content

- 카테고리 중 인기 팟 보기 카테고리 추가
- 최근 본 팟 리스트 조회 로직 추가
- 해시태그 로직 추가

## ✅ TODO

- [ ] 최근 본 팟 리스트 조회 로직 추가
- [ ] 카테고리 중 인기 팟 보기 카테고리 추가
- [ ] 해시태그 로직 추가
