### ISSUE TITLE
[feat] spring rest docs + swagger UI 도입

### ISSUE THREAD

**Issue by junchanpp** [iTpple-S-POT/backend#7]
## 📝 Content
- spring rest docs 추가
- swagger UI 추가
## ✅ TODO
- [ ] spring rest docs 추가
- [ ] swagger UI 추가
- [ ] 테스트 api 작성
