### ISSUE TITLE
Exception 처리 환경 구축

### ISSUE THREAD

**Issue by sujeong11** [iTpple-S-POT/backend#8]
## 📝 Content
- `@RestControllerAdvice`를 활용해 어플리케이션에서 발생하는 예외를 처리하기 위한 환경을 구축한다.
## ✅ TODO
- [ ] @RestControllerAdvice 활용한 에러 처리 환경 구축
- [ ] CustomException 클래스 생성
- [ ] 에러 내용을 관리할 ErrorCode 클래스 생성
