### ISSUE TITLE
pot 신고하기 추가

### ISSUE THREAD

**Issue by junchanpp** [iTpple-S-POT/backend#93]
## 📝 Content

- 팟 신고하기 기능 추가 및 신고에 따른 팟 숨김 로직 추가

## ✅ TODO

- [x] 팟 신고하기 기능 추가
- [x] 팟 검색 로직에서 신고한 팟은 제외
- [x] 팟 최근 본 리스트 로직에서 신고한 팟은 제외
